name: Train and Generate GPT-2 Model

on:
  push:
    branches:
      - main

jobs:
  train-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow transformers

      - name: Train model
        run: |
          python train.py --input-file input.txt --epochs 2

      - name: Generate text
        id: generate-text
        run: |
          python generate_text.py --model-dir model --max-length 100 --prompt-text "服务生也兴奋着两手揉着我的奶子干着我说：“好大的奶子，真的好软，骚穴好紧好会吸喔干的好爽喔”"

      - name: Create archive
        id: create-archive
        run: |
          tar -czvf output.tar.gz model/ generated_text.txt

      - name: Upload archive to release
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./output.tar.gz
          asset_name: output.tar.gz
          asset_content_type: application/gzip

      - name: Display generated text
        run: cat generated_text.txt

      - name: Display download link
        run: echo "Download link https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/output.tar.gz"
